#ifndef _DEFINITIONS
#define _DEFINITIONS

#define BOOL char
#define TRUE 1
#define FALSE 0

#define INSTRUCTIONS_DEPTH 4096
#define LINE_MAX_LENGTH_IN_BYTES 500
#define LABEL_MAX_LENGTH 50
#define INSTRUCTION_SIZE_IN_BITS 48

#endif